import { useEffect, useState } from "react";
import { Download, Mail, CheckCircle2, Pencil } from "lucide-react";
import { toast } from "sonner";
import { type Estimate, updateEstimate } from "../../../src/features/estimating/api";
import { getClient } from "../../../src/features/clients/api";

const money = (cents?: number | null) => new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD", maximumFractionDigits: 0 }).format((cents || 0) / 100);

export default function EstimateSheetScreen({ estimate, onRefresh }: { estimate: Estimate; onRefresh: () => void }) {
  const [client, setClient] = useState<any>(null);
  const [editing, setEditing] = useState(false);
  const [scope, setScope] = useState(estimate.scope_of_work || "");
  const [terms, setTerms] = useState(estimate.estimate_terms || "Estimate valid for 30 days. Changes outside this scope require written approval and may affect price and schedule.");
  useEffect(() => { getClient(estimate.client_id).then(setClient).catch(() => null); }, [estimate.client_id]);
  const save = async () => { try { await updateEstimate(estimate.id, { scope_of_work: scope, estimate_terms: terms, proposal_approved: true, status: "proposal_sent" } as any); setEditing(false); onRefresh(); toast.success("Estimate saved"); } catch (e: any) { toast.error(e?.message || "Could not save estimate"); } };
  const send = async () => { if (!client?.email) return toast.error("Add a client email before sending"); await updateEstimate(estimate.id, { estimate_sent_at: new Date().toISOString(), proposal_approved: true, status: "proposal_sent" } as any); const subject = encodeURIComponent(`Cstle estimate — ${estimate.name}`); const body = encodeURIComponent(`Hi ${client.name || "there"},\n\nYour Cstle estimate for ${estimate.name} is ready. The estimate total is ${money(estimate.agreed_price_cents)}.\n\nPlease reply with any questions.\n\nCstle Construction`); window.location.href = `mailto:${client.email}?subject=${subject}&body=${body}`; onRefresh(); };
  return <div className="space-y-4">
    <div className="flex items-center justify-between gap-3"><div><p className="font-['Roboto_Mono'] text-[9px] font-bold uppercase tracking-[0.12em] text-[#65733d]">03 · Ready</p><h1 className="mt-1 text-[23px] font-semibold tracking-[-0.035em] text-[#191919] sm:text-[30px]">A clean estimate, ready to send.</h1></div><CheckCircle2 className="size-6 text-[#65733d]" /></div>
    <article id="cstle-estimate-sheet" className="overflow-hidden rounded-2xl border border-black/[0.08] bg-white shadow-[0_24px_70px_rgba(25,28,18,.08)] print:shadow-none">
      <div className="flex items-start justify-between gap-6 border-b border-black/[0.07] p-5 sm:p-8"><div><p className="text-[23px] font-bold tracking-[-0.04em]">cstle</p><p className="font-['Roboto_Mono'] text-[8px] uppercase tracking-[0.2em] text-black/45">Construction</p></div><div className="text-right"><p className="font-['Roboto_Mono'] text-[9px] uppercase text-black/40">Estimate</p><p className="mt-1 text-[13px] font-semibold">EST-{estimate.id.slice(0, 8).toUpperCase()}</p><p className="mt-1 text-[9px] text-black/40">{new Date().toLocaleDateString("en-CA")}</p></div></div>
      <div className="grid gap-6 p-5 sm:grid-cols-2 sm:p-8"><div><p className="font-['Roboto_Mono'] text-[8px] font-bold uppercase tracking-[0.12em] text-black/35">Prepared for</p><p className="mt-2 text-[14px] font-semibold">{client?.name || "Client"}</p><p className="mt-1 text-[10px] leading-relaxed text-black/50">{client?.email}<br />{estimate.site_address}</p></div><div className="sm:text-right"><p className="font-['Roboto_Mono'] text-[8px] font-bold uppercase tracking-[0.12em] text-black/35">Project</p><p className="mt-2 text-[14px] font-semibold">{estimate.name}</p></div></div>
      <div className="border-y border-black/[0.07] bg-[#fafaf7] p-5 sm:p-8"><div className="flex items-center justify-between"><p className="font-['Roboto_Mono'] text-[8px] font-bold uppercase tracking-[0.12em] text-black/35">Scope of work</p><button onClick={() => setEditing((v) => !v)} className="print:hidden"><Pencil className="size-3.5 text-black/35" /></button></div>{editing ? <textarea value={scope} onChange={(e) => setScope(e.target.value)} rows={8} className="mt-3 w-full rounded-lg border border-black/10 bg-white p-3 text-[11px] leading-relaxed outline-none" /> : <p className="mt-3 whitespace-pre-wrap text-[11px] leading-[1.75] text-black/70">{scope}</p>}</div>
      <div className="p-5 sm:p-8"><div className="ml-auto max-w-sm"><div className="flex items-end justify-between border-b border-black/[0.08] pb-4"><span className="text-[12px] text-black/50">Estimate total</span><span className="text-[30px] font-semibold tracking-[-0.045em] tabular-nums text-[#20251a]">{money(estimate.agreed_price_cents)}</span></div><p className="mt-2 text-right font-['Roboto_Mono'] text-[8px] uppercase text-black/35">CAD · taxes shown on final invoice where applicable</p></div><div className="mt-8"><p className="font-['Roboto_Mono'] text-[8px] font-bold uppercase tracking-[0.12em] text-black/35">Terms</p>{editing ? <textarea value={terms} onChange={(e) => setTerms(e.target.value)} rows={3} className="mt-2 w-full rounded-lg border border-black/10 p-3 text-[10px] outline-none" /> : <p className="mt-2 text-[9px] leading-relaxed text-black/45">{terms}</p>}</div></div>
    </article>
    {editing && <button onClick={save} className="w-full rounded-xl bg-[#65733d] py-3 text-[11px] font-semibold text-white">Save changes</button>}
    <div className="grid grid-cols-2 gap-2 print:hidden"><button onClick={() => window.print()} className="flex min-h-12 items-center justify-center gap-2 rounded-xl border border-black/10 bg-white text-[11px] font-medium shadow-sm"><Download className="size-4" /> PDF / Print</button><button onClick={send} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#65733d] text-[11px] font-semibold text-white shadow-[0_12px_28px_rgba(66,77,36,.24)]"><Mail className="size-4" /> Send estimate</button></div>
    <p className="text-center font-['Roboto_Mono'] text-[8px] uppercase tracking-[0.08em] text-black/35">Sending opens the device email app. Delivery tracking comes next.</p>
  </div>;
}
